### ISSUE TITLE
Statik

### ISSUE THREAD

**Issue by margaretjansen** [XZB-1248/Spark#13]
┌──(pentester㉿lab01)-[~/opt/Spark]
└─$ statik -m -src="./built" -f -dest="./server/embed" -include=* -p built -ns built
flag provided but not defined: -include
Usage of statik:

**Comment by margaretjansen** [comment]
Solution was simple. After installing statik it was not added to my path.
I removed golang-statik
┌──(pentester㉿lab01)-[~/opt/Spark]
└─$ ~/go/bin/statik -m -src="./web/dist" -f -dest="./server/embed" -p web -ns web

**Comment by XZB-1248** [comment]
Hi there.
In fact, there's no need to embed all clients file into servers.
So `statik -m -src="./built" -f -dest="./server/embed" -include=* -p built -ns built` is no longer necessary.

I've forgotten to update the document, that's my fault :).
