### ISSUE TITLE
建议服务端和前端分离

### ISSUE THREAD

**Issue by 91th4b** [XZB-1248/Spark#15]
建议服务端和前端分离，前端部署到无服务器应用,比如部署到cloudflare workers上。增加socks5就更加完美了。

**Comment by XZB-1248** [comment]
真要搞的话，技术上没问题，但是有以下几点比较麻烦：
* 前端资源太大，服务端现在加了gzip，如果要放到workers上，也要加对应的代码
* 对于刚入门的人来说不太友好

不过等我有空，应该会改一下，比如把前端资源单独打包成一份release，顺便完善一下wiki

**Comment by XZB-1248** [comment]
现在你如果要这么改的话倒也不难：
手动编译前端
写一下API的反向代理
做好workers的缓存、gzip压缩

做好这几步基本上就可以了
