### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by 98Kstar** [XZB-1248/Spark#16]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [X] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [X] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

v0.1.1

### Describe the bug / 问题描述

师傅好，我在使用过程中发现个问题，系统为linux，有流量监控，控制面板使用cpanel，在实际操作中，先后使用该cpanel的两个不同账号登录到cpanel后台，使用cpaenl的termit将spark的client执行，发现在同时该台机器只能够上线一个用户，即：我使用A用户上线到spark后，B用户在spark上的进程就失效。A，B用户所使用的client名不同，所放文件夹位置也不同，不知道是否是个bug，望解答，谢谢。

### Reproduction / 复现方式

先后使用该cpanel的两个不同账号登录到cpanel后台，使用cpaenl的termit将spark的client执行，发现在同时该台机器只能够上线一个用户，即：我使用A用户上线到spark后，B用户在spark上的进程就失效。A，B用户所使用的client名不同，所放文件夹位置也不同，不知道是否是个bug，望解答，谢谢。

**Comment by XZB-1248** [comment]
不是bug，设计之初就是这么考虑的，每个设备只会同时运行一个客户端。运行两个客户端的话，第一个客户端会在第二个运行之后下线。

**Comment by 98Kstar** [comment]
好的，收到，感谢。
