### ISSUE TITLE
Feature Request: 远程桌面

### ISSUE THREAD

**Issue by lwd-temp** [XZB-1248/Spark#17]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [X] I'm sure this feature is not implemented.
- [x] 我确定该功能尚未实现。
- [X] I'm sure it's a reasonable and popular requirement.
- [x] 我确定这个需求合理且符合大多数人需要。

### Describe the feature / 需求描述

适用于Windows的实时远程桌面功能

**Comment by XZB-1248** [comment]
这确实是个刚需，不过，碍于技术问题，还需要一段时间才可能上线。算是一个todo吧。
