### ISSUE TITLE
增加反向代理的支持

### ISSUE THREAD

**Issue by zwz** [XZB-1248/Spark#2]
因为服务器有一些限制
我在使用nginx作为反向代理
我想在访问路径/spark时代理给本应用
不知道有没有可能增加这个支持

**Comment by XZB-1248** [comment]
一直都可以。只要反代的时候把websocket加上，设置一下max_body_size，禁用proxy_request_buffering就行。
以下配置中的端口需要自行修改。

```
location ^~ /spark/
{
  proxy_request_buffering off;
  client_max_body_size 1024g;
  proxy_cache off;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_set_header X-Forwarded-For $remote_addr;
  proxy_pass http://127.0.0.1:8080/;
  add_header Pragma "no-cache";
  add_header Cache-Control "no-cache";
}
```

**Comment by XZB-1248** [comment]
哦对了，生成客户端的时候，路径一般会自动填写，一般**不需要**自己修改。

**Comment by zwz** [comment]
嗯，好的，谢谢，已经可以了
但是进去后，首页主机名 | 用户名等都是“暂无数据”
然后客户端生成后运行提示“websocket: bad handshake”
是不是因为我的主机在堡垒机之后的原因？

**Comment by XZB-1248** [comment]
看样子是ws连接失败，不过一般来说都不会特地阻断websocket。
你可以先试下在客户机上访问主机的控制面板，看下能不能访问。
具体情况具体分析。
