### ISSUE TITLE
交互式cmd shell

### ISSUE THREAD

**Issue by wgetnz** [XZB-1248/Spark#20]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [ ] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [ ] I'm sure this feature is not implemented.
- [ ] 我确定该功能尚未实现。
- [ ] I'm sure it's a reasonable and popular requirement.
- [ ] 我确定这个需求合理且符合大多数人需要。

### Describe the feature / 需求描述

交互式shell比较方便，大多数人应该需要

**Comment by XZB-1248** [comment]
如果你是指像linux那样的完整的交互，那必须借助winpty之类的依赖。
而且客户端还必须拖着额外的dll和exe，显然不在项目的考虑范围内。

更何况，Windows不是一直都可以使用终端功能吗？
最新的release，在前端方面已经实现了cmd上下左右这些最基本的交互。
