### ISSUE TITLE
运行终端client客户端会弹出cmd.exe的黑框? 能去掉吗

### ISSUE THREAD

**Issue by 91ssvip** [XZB-1248/Spark#21]
### Please make sure of the following things.

- [ ] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [ ] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [ ] I'm sure there are no duplicate issues.
- [ ] 我确定没有提交和他人重复的issue。
- [ ] I'm sure this feature is not implemented.
- [ ] 我确定该功能尚未实现。
- [ ] I'm sure it's a reasonable and popular requirement.
- [ ] 我确定这个需求合理且符合大多数人需要。

**Comment by XZB-1248** [comment]
可以，但是不会改。
vbs，创建服务，start命令，任君选择。
毕竟，对于正常用户，上面的办法足够用了。
不提供这些可能导致项目被用来恶意使用的功能。
虽说有心人真要这么耍的话我也拦不住。

**Comment by introspection3** [comment]
给我写一个cmd可以让我指定的路径的exe开机自动执行,并且可以隐藏
