### ISSUE TITLE
FEATURE REQUEST FOR SAVED PASSWORDS

### ISSUE THREAD

**Issue by smfai200** [XZB-1248/Spark#24]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [ ] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [ ] 我确定没有提交和他人重复的issue。
- [X] I'm sure this feature is not implemented.
- [ ] 我确定该功能尚未实现。
- [X] I'm sure it's a reasonable and popular requirement.
- [ ] 我确定这个需求合理且符合大多数人需要。

### Describe the feature / 需求描述

Collect Saved Passwords from Chrome, Moxilla etc

**Comment by XZB-1248** [comment]
Hi, this feature won’t be implemented.
Google are testing to encrypt these data, stealing passwords is difficult in the future.
And this feature is illegal in China because it violates people's privacy.
