### ISSUE TITLE
linux 每次启动终端，都会多一个 /bin/bash进程

### ISSUE THREAD

**Issue by y35uishere** [XZB-1248/Spark#28]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [X] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [X] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

111

### Describe the bug / 问题描述

linux 每次启动终端，都会多一个 /bin/bash进程
不知不觉，一堆 /bin/bash

应该退出自动kill

### Reproduction / 复现方式

linux 每次启动终端，都会多一个 /bin/bash进程
不知不觉，一堆 /bin/bash

应该退出自动kill

11111111111111111111111111111111111111111111111111111111111111
1
1
1
1
1

### Logs / 日志

```shell
1111111111111111111111111111111111
```

### Additional information / 附加说明

111111111111111111111111111111

**Comment by XZB-1248** [comment]
已找到问题，将会在下个版本修复。
