### ISSUE TITLE
文件列表，按钮优化

### ISSUE THREAD

**Issue by y35uishere** [XZB-1248/Spark#31]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [X] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [X] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

V0.1.8

### Describe the bug / 问题描述

删除和编辑在一起。

很容易想编辑，却碰到了删除。
建议，下载，编辑在外面一起展示。

删除在...点点点里面
太危险了、、、、、

### Reproduction / 复现方式

11111111111

**Comment by XZB-1248** [comment]
已经将删除按钮放到最底下。
其实删除文件的时候会有二次询问，不需要担心误触的问题。
