### ISSUE TITLE
截屏操作时会出现BitBlt failed异常,请问一下

### ISSUE THREAD

**Issue by Meow-Cat** [XZB-1248/Spark#32]
### Please make sure of the following things.

- [ ] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [ ] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [ ] I'm sure there are no duplicate issues.
- [ ] 我确定没有提交和他人重复的issue。
- [ ] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [ ] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

v0.1.2

### Describe the bug / 问题描述

<img width="795" alt="CFE7DA33-4759-4B79-A37E-777167D5C72D" src="https://user-images.githubusercontent.com/48432520/199144648-ae80c621-d1e2-413b-b620-7afdd7a18f68.png">

### Reproduction / 复现方式

客户端连接时间过长时会出现

**Comment by XZB-1248** [comment]
客户端用的是GDI截图，需要和桌面进行交互。
如果放在服务器上，断开连接后就会无法截图。
如果设置为计划任务或者服务，一般也无法截图。
