### ISSUE TITLE
linux 远程桌面无画面

### ISSUE THREAD

**Issue by yayalor** [XZB-1248/Spark#35]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [X] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [X] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

v最新

### Describe the bug / 问题描述

生成linux 客户端， 在server端上线后，远程桌面无法正常工作，具体表现是无画面。 windows客户端不会有这个问题

### Reproduction / 复现方式

生成Linux客户端，上线-> 桌面功能

**Comment by XZB-1248** [comment]
感谢测试，我已经在新版本里修改了这部分的代码，同样的代码在windows下已经正常。
