### ISSUE TITLE
客户端是windows，服务端查看客户端桌面报错

### ISSUE THREAD

**Issue by try3** [XZB-1248/Spark#38]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [X] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [X] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

v0.2.1

### Describe the bug / 问题描述

客户端是windows，服务端查看客户端桌面报错![image](https://user-images.githubusercontent.com/17698581/223949561-a35be8ca-ee32-465a-90f7-353f29653f4c.png)

### Reproduction / 复现方式

服务端查看客户端的桌面

### Logs / 日志

```shell
无
```

### Additional information / 附加说明

无

**Comment by XZB-1248** [comment]
可能是截图失败但是client没有判断。
我会在下个版本里加上相应的检测逻辑。
