### ISSUE TITLE
期望加上端口和进程监控

### ISSUE THREAD

**Issue by DarkiT** [XZB-1248/Spark#4]
如题，期望加上端口和进程监控

**Comment by XZB-1248** [comment]
具体点呢？具体怎么监控？

**Comment by DarkiT** [comment]
其实就是想弄一个简单的监控，启动服务端后可以给接入的节点添加需要监控的进程或者是端口，然后定期让客户端进程上报当前的全部端口或者进程进行比较，如果达到配置中的告警阈值，就向指定的web接口上推送一个警告消息即可。不过这么一来好像就必须要数据库支持或者是对设置了监控的节点写配置文件了。

**Comment by XZB-1248** [comment]
以后应该会考虑加上这个功能，不过最近肯定是不会考虑的。
