### ISSUE TITLE
ubuntu 22.10无法启动

### ISSUE THREAD

**Issue by jjyou-github** [XZB-1248/Spark#41]
### Please make sure of the following things.

- [ ] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [ ] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [ ] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [X] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

0.2.1

### Describe the bug / 问题描述

ubuntu 22.10无法启动

### Reproduction / 复现方式

![image](https://user-images.githubusercontent.com/63731955/226345594-76b27bf1-1574-4c02-9554-70376b826fdc.png)
![image](https://user-images.githubusercontent.com/63731955/226346540-a41e095a-90e9-4f4e-8773-00239e0c85b5.png)

**Comment by XZB-1248** [comment]
配置文件的listen字段，是包含了host和端口的，格式应该为host:port。
例如，要监听8000端口，那么应该填写0.0.0.0:8000，或者:8000，而不是仅仅只有一个端口号。

**Comment by jjyou-github** [comment]
> 配置文件的listen字段，是包含了host和端口的，格式应该为host:port。 例如，要监听8000端口，那么应该填写0.0.0.0:8000，或者:8000，而不是仅仅只有一个端口号。

感谢回复：
1.按你的方法重新配置文件后可正常启动和访问了
2.你主页示例部分的listen就是只有端口，麻烦确认后完善。

**Comment by XZB-1248** [comment]
> > 配置文件的listen字段，是包含了host和端口的，格式应该为host:port。 例如，要监听8000端口，那么应该填写0.0.0.0:8000，或者:8000，而不是仅仅只有一个端口号。
> 
> 感谢回复： 1.按你的方法重新配置文件后可正常启动和访问了 2.你主页示例部分的listen就是只有端口，麻烦确认后完善。

文档里也是":8000"，所以文档其实是没写错的
![0](https://user-images.githubusercontent.com/28593573/226815927-20721e74-2373-40d3-af2d-4cc82c213ac9.png)

**Comment by XZB-1248** [comment]
> 不好意思，再次请教，生成客户端时没有地方输入用户名、密码。 在客户端运行无法连接，服务器端报错用户名为空，这个要怎么解决？ ![image](https://user-images.githubusercontent.com/63731955/226653917-c1ebd7a5-8157-4cdd-9b1a-57f1a8bdb96c.png) ![image](https://user-images.githubusercontent.com/63731955/226654148-1b84fd48-4627-4dcb-9d16-053920cca8af.png)
> 
> ![image](https://user-images.githubusercontent.com/63731955/226654525-10192383-b3dd-40a2-944c-3c75b7e656af.png)

客户端连接服务端是不需要用户名和密码的。
LOGIN_ATTEMPT事件只有通过webui登录的时候才会触发，所以这个事件不是客户端的连接造成的
至于客户端连接失败，原因有很多，或许可以考虑更换端口、重新生成客户端。
生成的时候默认会填好相关信息，一般不需要修改

**Comment by lovemz** [comment]
> 配置文件的listen字段，是包含了host和端口的，格式应该为host:port。 例如，要监听8000端口，那么应该填写0.0.0.0:8000，或者:8000，而不是仅仅只有一个端口号。
[root@ local]#
[root@ local]# ./server_linux_amd64
[INFO] 2023/03/25 21:27:53 {"event":"SERVICE_INIT","listen":"0.0.0.0:8000"}

  不知道为什么8000 端口就是起不来， win系统的服务端正常

**Comment by iamblackcat** [comment]
> > 配置文件的listen字段，是包含了host和端口的，格式应该为host:port。 例如，要监听8000端口，那么应该填写0.0.0.0:8000，或者:8000，而不是仅仅只有一个端口号。
> > [root@ local]#
> > [root@ local]# ./server_linux_amd64
> > [INFO] 2023/03/25 21:27:53 {"event":"SERVICE_INIT","listen":"0.0.0.0:8000"}
> 
> 不知道为什么8000 端口就是起不来， win系统的服务端正常

netstat -ano检查一下端口正常启动了吗？如果正常可以看看防火墙规则是否放行了
