### ISSUE TITLE
How can i run it in background

### ISSUE THREAD

**Issue by Unknownio** [XZB-1248/Spark#42]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [ ] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [ ] 我确定没有提交和他人重复的issue。
- [X] I'm sure this feature is not implemented.
- [ ] 我确定该功能尚未实现。
- [X] I'm sure it's a reasonable and popular requirement.
- [ ] 我确定这个需求合理且符合大多数人需要。

### Describe the feature / 需求描述

How can i make it run in background?
i like this rat but it would to more cool if there was option to run in background

**Comment by XZB-1248** [comment]
Well, there's no option to make the client run in daemon mode, yet.
When I firstly set up this project, I want to use it on my all devices, so this option is not really necessary.
However, this feature may be implemented in the future, as there are several issues related to it.
