### ISSUE TITLE
使用主机名而不是用户名作为识别客户端的唯一值

### ISSUE THREAD

**Issue by kuerme** [XZB-1248/Spark#48]
### Please make sure of the following things.

- [ ] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [ ] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [ ] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [X] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

v0.2.1

### Describe the bug / 问题描述

当Windows客户端的用户名相同时，Spark只会识别1个客户端，其他同名客户端会强制被退出； 建议以客户端主机名为唯一值，而不是用户名；

### Reproduction / 复现方式

在虚机环境中，使用同用户名的客户机启动client.exe； Spark服务器后端有且只会展示最后一个运行client.exe的客户机；

**Comment by XZB-1248** [comment]
这并不是bug，是故意为之。
设计之初就设定了不能多次运行。
识别设备靠的是machineID，如果服务端发现相同ID已经在线，会发送指令让前者下线。

现在所有的操作都靠machineID，如果要修改的话，基本上不可能了，除非推倒重来。

**Comment by XZB-1248** [comment]
如果只是同用户名，应该是不会让其他设备退出的。可能是虚拟机和物理机获取到的machineID相同，导致另一个设备被迫下线。

**Comment by kuerme** [comment]
嗯，刚刚已经发现了，并不是通过用户名，而应该时你说的MachineID； 我发现彻底更改用户名后还是会被下线； 我现在试下能否在虚机里吗MachineID改掉；

**Comment by kuerme** [comment]
@XZB-1248 麻烦关闭掉这个Issue，这个功能没毛病；

**Comment by fantasylidong** [comment]
补充一下MachineID修改办法：
1、以管理员模式运行regedit
2、MachineID位于 **计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography** 位置
3、使用uuid生成网页生成uuid进行替换
