### ISSUE TITLE
请确认下，不知道是不是误报😂

### ISSUE THREAD

**Issue by Ran-Xing** [XZB-1248/Spark#5]
不要用这些风险平台给自己加麻烦

https://x.threatbook.cn/v5/ip/91.189.94.4
https://x.threatbook.cn/v5/ip/3.228.155.36

**Comment by XZB-1248** [comment]
所以这是什么意思呢？

**Comment by Ran-Xing** [comment]
zeek 抓包获取到的，是不是什么 静态资源托管平台啥的 IP 被标记了吧 @XZB-1248

**Comment by XZB-1248** [comment]
按理来说，这套系统是完全不需要外网的，包括前端。
前端的所有资源也是由服务端直接提供的，没有使用外部CDN。
你确定是程序访问了外部CDN？
或者，提供一下具体操作步骤？我看一下

**Comment by Ran-Xing** [comment]
复现的前提，一台干净的 虚拟机，不然别的误报就尴尬了

docker 安装 可以参考 [gist](https://gist.github.com/Ran-Xing/b7eef746736e51d6f7c6fd24dd942b5d)

先docker 启动一个[zeek](https://github.com/XRSec/Docker_Zeek) docker-compose 把其他的服务删了，配置下网卡，启动

然后 运行你的 软件

接着在zeek 日志处把所有IP拷贝出来，正则匹配。去重，去掉本地IP

一个一个上 微步搜 服务商去掉

**Comment by Ran-Xing** [comment]
有点麻烦，我估计十有八九就是 一些 CDN文件 导致的，但是微步 又没更新这些cdn厂商信息
嫌弃麻烦的话要不试试 mitxxxproxy 直接设置代理启动抓包看看都有哪些IP
https://github.com/mitmproxy/mitmproxy

**Comment by XZB-1248** [comment]
![1](https://user-images.githubusercontent.com/28593573/168453011-16a09ab0-e2e2-487b-b77b-08c07b7c1cc3.png)
![2](https://user-images.githubusercontent.com/28593573/168453012-1c25be20-17bf-4aee-9d23-0f60e8765d13.png)
![3](https://user-images.githubusercontent.com/28593573/168453013-c29dcf10-7100-4364-90d0-c663bba13b37.png)

**如你所见，这个IP，大概率是ubuntu的ntp服务器，与我无关。**
**这套项目不会请求任何第三方服务，至少，在依赖项没被下毒的情况下。**
**服务端不必多说，前端的静态资源也全部由服务端提供。**
**所以，大可放心使用。**
