### ISSUE TITLE
Web panel inaccessible

### ISSUE THREAD

**Issue by gray-pear** [XZB-1248/Spark#52]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [ ] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [ ] 我确定没有提交和他人重复的issue。
- [ ] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [ ] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

Latest from github

### Describe the bug / 问题描述

The webpanel is inaccessible. I downloaded the server_linux_amd64 file, executed it with a config on port 8001, and the web panel was inaccessible. No errors. nothing popped up. port showed up as closed on a port checker
The port is forwarded

### Reproduction / 复现方式

1-Get Spark
2-Run the Spark file
3-View that the web panel is inaccessible

### Additional information / 附加说明

Fedora server

**Comment by XZB-1248** [comment]
Please show me your config file and netstat, so I can try to find out what happened.
