### ISSUE TITLE
无法使用网页关机电脑

### ISSUE THREAD

**Issue by fantasylidong** [XZB-1248/Spark#55]
### Please make sure of the following things.

- [ ] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [ ] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [ ] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [ ] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

v0.2.1

### Describe the bug / 问题描述

使用Spark网页关闭电脑时，无法进行关闭
![image](https://github.com/XZB-1248/Spark/assets/22582796/d6a6342c-f022-41e6-af27-4f5b3378da96)
出现这个提示

### Reproduction / 复现方式

网页关机对应电脑

### Logs / 日志

```shell
系统是
版本	Windows 10 专业工作站版
版本号	22H2
安装日期	‎2023/‎5/‎19
操作系统内部版本	19045.2913
体验	Windows Feature Experience Pack 1000.19041.1000.0
```

**Comment by XZB-1248** [comment]
目前已经加上了Force标志位，应该是能够解决问题。
下个版本发布后应该就可以修复了。
