### ISSUE TITLE
undefined: config.COMMIT

### ISSUE THREAD

**Issue by kuloutoussssss** [XZB-1248/Spark#62]
### Please make sure of the following things.

- [ ] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [X] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [ ] I'm sure there are no duplicate issues.
- [X] 我确定没有提交和他人重复的issue。
- [ ] I'm sure this feature is not implemented.
- [X] 我确定该功能尚未实现。
- [ ] I'm sure it's a reasonable and popular requirement.
- [X] 我确定这个需求合理且符合大多数人需要。

### Describe the feature / 需求描述

./build.client.sh
# Spark/client/core
../client/core/core.go:115:16: undefined: config.COMMIT
../client/core/core.go:122:34: undefined: config.COMMIT
# Spark/client/core
../client/core/core.go:115:16: undefined: config.COMMIT
../client/core/core.go:122:34: undefined: config.COMMIT
# Spark/client/core
../client/core/core.go:115:16: undefined: config.COMMIT
../client/core/core.go:122:34: undefined: config.COMMIT
# Spark/client/core
../client/core/core.go:115:16: undefined: config.COMMIT
../client/core/core.go:122:34: undefined: config.COMMIT

### Suggested solution / 实现思路

这是什么错误导致的呢？

**Comment by XZB-1248** [comment]
已修复，修改了config，但是没改完全
