### ISSUE TITLE
功能增强

### ISSUE THREAD

**Issue by go-bi** [XZB-1248/Spark#7]
可以参考下比较成熟的https://github.com/BishopFox/sliver功能。

**Comment by romotc** [comment]
有计划继续完善吗？
比如：CPU、内存、网络历史占用曲线图，CPU温度监控等功能

**Comment by romotc** [comment]
另外现在好像会造成客户端假死

**Comment by XZB-1248** [comment]
> 另外现在好像会造成客户端假死

客户端假死？可以提供一下具体的复现步骤么？

**Comment by romotc** [comment]
> > 另外现在好像会造成客户端假死
> 
> 客户端假死？可以提供一下具体的复现步骤么？

就是一打开客户端工控机就假死，屏幕亮但是任何鼠标键盘操作都没有反应。不确定是不是工控机配置太低导致的，我回头再试试把服务器端放在另外一台电脑上，工控机只运行客户端试试。
